version: "3.8"

services:
  database:
    container_name: trainee_database
    image: postgres:latest
    ports: 
      - 5432:5432
    env_file: ./.env
    volumes:
      - ./local/pgdata:/var/lib/postgresql/data
    networks:
      - poke-manager

  crawler:
    container_name: pokemon_crawler
    image: node
    volumes:
      - ./core:/core
      - ./crawler:/project
    depends_on:
      - database
    working_dir: /project
    env_file: ./.env
    entrypoint: npm run app
    environment: 
      - POSTGRES_HOST=database
    networks:
      - poke-manager
  
  core:
    container_name: pokemon_core
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./core:/project
    depends_on:
      - database
    working_dir: /project
    env_file: ./.env
    entrypoint: npm run app
    environment: 
      - POSTGRES_HOST=database
    networks:
      - poke-manager

networks:
  poke-manager:
